<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nate Latshaw">
<meta name="dcterms.date" content="2025-03-02">
<meta name="description" content="An advanced striking metric that is easily interpreted, offers new insights, and facilitates meaningful comparisons between fighters">

<title>LiteralFightNerd - Introducing Strike Accuracy Over Expected (SAOE)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="LiteralFightNerd - Introducing Strike Accuracy Over Expected (SAOE)">
<meta property="og:description" content="An advanced striking metric that is easily interpreted, offers new insights, and facilitates meaningful comparisons between fighters">
<meta property="og:image" content="https://literalfightnerd.com/posts/2025-03-02-introducing-strike-accuracy-over-expected/img/saoe-table.png">
<meta property="og:site-name" content="LiteralFightNerd">
<meta property="og:image:height" content="1164">
<meta property="og:image:width" content="2352">
<meta name="twitter:title" content="LiteralFightNerd - Introducing Strike Accuracy Over Expected (SAOE)">
<meta name="twitter:description" content="An advanced striking metric that is easily interpreted, offers new insights, and facilitates meaningful comparisons between fighters">
<meta name="twitter:image" content="https://literalfightnerd.com/posts/2025-03-02-introducing-strike-accuracy-over-expected/img/saoe-table.png">
<meta name="twitter:creator" content="@NateLatshaw">
<meta name="twitter:image-height" content="1164">
<meta name="twitter:image-width" content="2352">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">LiteralFightNerd</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-my-other-websites" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">My Other Websites</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-my-other-websites">    
        <li>
    <a class="dropdown-item" href="https://natelatshaw.shinyapps.io/ufc_fight_night_statistical_companion/" rel="" target="">
 <span class="dropdown-text">UFC Fight Night Statistical Companion</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://natelatshaw.shinyapps.io/ufc-dfs-simulator-and-optimizer/" rel="" target="">
 <span class="dropdown-text">FightPickSim - A Premium UFC DFS Tool</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.mmaoddsbreaker.com/mmaoddsbreaker-tale-of-the-tape/" rel="" target="">
 <span class="dropdown-text">MMAOB Tale of the Tape</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://linktr.ee/natelatshaw" rel="" target="">
 <span class="dropdown-text">Linktree</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://twitter.com/NateLatshaw" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text">Twitter</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.linkedin.com/in/nathaniel-latshaw/" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text">LinkedIn</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Introducing Strike Accuracy Over Expected (SAOE)</h1>
                  <div>
        <div class="description">
          <p>An advanced striking metric that is easily interpreted, offers new insights, and facilitates meaningful comparisons between fighters</p>
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Nate Latshaw </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">March 2, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#motivation-why-strike-accuracy-is-limited" id="toc-motivation-why-strike-accuracy-is-limited" class="nav-link" data-scroll-target="#motivation-why-strike-accuracy-is-limited">Motivation: why strike accuracy is limited</a></li>
  <li><a href="#calculating-strike-accuracy-over-expected-saoe" id="toc-calculating-strike-accuracy-over-expected-saoe" class="nav-link" data-scroll-target="#calculating-strike-accuracy-over-expected-saoe">Calculating Strike Accuracy Over Expected (SAOE)</a></li>
  <li><a href="#how-saoe-improves-upon-strike-accuracy" id="toc-how-saoe-improves-upon-strike-accuracy" class="nav-link" data-scroll-target="#how-saoe-improves-upon-strike-accuracy">How SAOE improves upon strike accuracy</a></li>
  <li><a href="#components-of-saoe" id="toc-components-of-saoe" class="nav-link" data-scroll-target="#components-of-saoe">Components of SAOE</a></li>
  <li><a href="#limitations-of-saoe" id="toc-limitations-of-saoe" class="nav-link" data-scroll-target="#limitations-of-saoe">Limitations of SAOE</a></li>
  <li><a href="#next-steps" id="toc-next-steps" class="nav-link" data-scroll-target="#next-steps">Next steps</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>The Ultimate Fighting Championship (UFC) recently introduced a <a href="https://www.ufc.com/news/does-striking-accuracy-accurately-measure-striking">new strike accuracy-related metric</a> for broadcasts. In short, certain types of strikes (e.g.&nbsp;power punches to the body from a mounted position) are easier to land than others (e.g.&nbsp;head kicks from distance). Since these different types of strikes land at significantly different rates, a fighter’s strike accuracy can be more a function of striking tendencies than an actual, informative measure of a fighter’s ability to land strikes.</p>
<p>To solve this limitation of strike accuracy as a metric, the UFC computes an expected strike accuracy based on both (a) the types of strikes that each fighter throws and (b) the rate at which each type of strike has landed historically across all fighters. Then, the difference between a fighter’s observed and expected strike accuracy is computed to serve as a more meaningful measure of accuracy.</p>
<p>This blog post utilizes this concept to formally introduce Strike Accuracy Over Expected (SAOE), a new metric that aims to quantify a fighter’s striking precision in a manner that improves upon the traditional strike accuracy metric. The details are provided below in this post, but put simply, SAOE has three desirable properties:</p>
<ol type="1">
<li><p><strong>SAOE is easily interpreted</strong> - it is interpreted as the percentage point difference between a fighter’s observed and expected strike accuracy.</p></li>
<li><p><strong>SAOE offers new insights</strong> - it contains a frame of reference for strike accuracy against which to compare to a fighter’s performance and wraps that up into a single, composite metric that quantifies striking precision.</p></li>
<li><p><strong>SAOE facilitates meaningful comparisons between fighters with different styles</strong> - it is correlated with strike accuracy but uncorrelated with striking tendencies.</p></li>
</ol>
<p>As a final note, the concept of SAOE is grounded in advanced analytics work from other sports. For instance, within the last couple years, National Football League (NFL) analysts have shown that a quarterback’s raw completion percentage is not strongly correlated with performance. In fact, some lower-quality quarterbacks have high completion percentages because they often throw short, safe passes. To improve upon completion percentage as a metric, <a href="https://www.the33rdteam.com/cpoe-explained/">Completion Percentage Over Expected (CPOE)</a> was developed. CPOE calculates the probability that a pass will be completed based on a number of factors (e.g.&nbsp;how far the ball travels in the air, the down and yards to go for a first down, etc.) and then computes the difference between a quarterback’s observed and expected completion percentage. Completing a high percentage of safe throws is not equivalent to completing the same percentage of challenging throws, and since CPOE is able to distinguish between the two, it has been shown to be a much more meaningful measure of quarterback performance.</p>
<p>With this blog post, we now have an advanced metric that is similar in concept and function to better quantify striking precision in the UFC.</p>
</section>
<section id="motivation-why-strike-accuracy-is-limited" class="level1">
<h1>Motivation: why strike accuracy is limited</h1>
<p>Strike accuracy, defined as the number of significant strikes a fighter lands divided by the number attempted, is easy to understand but is often not informative as a single measure of striking ability. Consider the figure below, which shows that distance strike accuracy is significantly lower than clinch and ground accuracy. Hence, an average fighter who only throws strikes from distance will have a lower strike accuracy than an average fighter who only throws strikes from the clinch and on the ground, and this difference would be purely due to striking tendencies rather than skill differences.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To further illustrate the point, the most common comparative use case of strike accuracy is (presumably) to determine which fighter is the more precise overall striker, and as such, strike accuracy as a metric can be problematic. The figure below shows that strike accuracy is negatively correlated with a fighter’s percent of significant strikes thrown at distance. Further, strike accuracy is positively correlated with a fighter’s percent of significant strikes thrown both from the clinch and on the ground. Thus, fighters who throw more strikes from distance tend to have lower strike accuracy, so when a kickboxer fights a grappler, comparing strike accuracy as a proxy for overall striking ability is likely to show the opposite of what is actually true.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Distance</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Clinch</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Ground</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>Finally, the table below shows the top 10 UFC fighters with the highest strike accuracy, among fighters with 300+ significant strike attempts and 1+ bouts since 2022. Many on this list are not necessarily considered elite strikers, and most throw a relatively small percent of strikes from distance, which indicates their strike accuracy is largely driven by striking tendencies rather than precision. As such, this top 10 list is not particularly relevant.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<caption>UFC Career Strike Accuracy Top 10 (among fighters with 300+ significant strike attempts and at least 1 bout since 2022)</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Fighter</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Strike accuracy</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Distance % of strike attempts</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Significant strikes attempts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Anthony Hernandez</td>
<td style="text-align: center;">63.4%</td>
<td style="text-align: center;">56.3%</td>
<td style="text-align: center;">748</td>
</tr>
<tr class="even">
<td style="text-align: center;">Alex Pereira</td>
<td style="text-align: center;">63.1%</td>
<td style="text-align: center;">86.9%</td>
<td style="text-align: center;">921</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Christian Leroy Duncan</td>
<td style="text-align: center;">62.5%</td>
<td style="text-align: center;">79.6%</td>
<td style="text-align: center;">363</td>
</tr>
<tr class="even">
<td style="text-align: center;">Shara Magomedov</td>
<td style="text-align: center;">62.4%</td>
<td style="text-align: center;">86.7%</td>
<td style="text-align: center;">633</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Chidi Njokuani</td>
<td style="text-align: center;">62.0%</td>
<td style="text-align: center;">61.4%</td>
<td style="text-align: center;">495</td>
</tr>
<tr class="even">
<td style="text-align: center;">Tatiana Suarez</td>
<td style="text-align: center;">61.7%</td>
<td style="text-align: center;">47.7%</td>
<td style="text-align: center;">472</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sean O'Malley</td>
<td style="text-align: center;">61.5%</td>
<td style="text-align: center;">95.8%</td>
<td style="text-align: center;">1,645</td>
</tr>
<tr class="even">
<td style="text-align: center;">Ciryl Gane</td>
<td style="text-align: center;">61.3%</td>
<td style="text-align: center;">92.3%</td>
<td style="text-align: center;">1,467</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Gunnar Nelson</td>
<td style="text-align: center;">61.1%</td>
<td style="text-align: center;">66.0%</td>
<td style="text-align: center;">453</td>
</tr>
<tr class="even">
<td style="text-align: center;">Phil Hawes</td>
<td style="text-align: center;">60.7%</td>
<td style="text-align: center;">79.9%</td>
<td style="text-align: center;">512</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Therefore, strike accuracy is limited in its ability to depict anything meaningful when (a) considering one fighter at a time, (b) comparing two fighters, and (c) attempting to rank fighters. Enter SAOE, a new and improved measure for overall striking precision.</p>
</section>
<section id="calculating-strike-accuracy-over-expected-saoe" class="level1">
<h1>Calculating Strike Accuracy Over Expected (SAOE)</h1>
<p><strong>SAOE is interpreted as the percentage point difference between observed and expected strike accuracy based on the types of strikes thrown</strong>. Positive numbers indicate fighters are more accurate than we would expect given their strike attempt distribution, and thus, elite strikers often rank highly in SAOE.</p>
<p>Understanding SAOE is as simple as comprehending the paragraph above. Now, the rest of this section gets mildly technical to show the computational details of the SAOE metric, so here is your warning if that is not of interest - you should be able to safely skip to the next section that showcases the importance of SAOE. For everyone else, I attempt to keep the forthcoming notation light and as readable as possible.</p>
<p>Mathematically, SAOE is calculated as follows:</p>
<p><span class="math display">\[
SAOE = \text{Significant strike accuracy} - \text{Expected significant strike accuracy}
\]</span></p>
<p>The only complexity underlying SAOE is then how to compute <em>expected</em> strike accuracy. The current version of SAOE separates distance, clinch, and ground strikes, and the expected accuracy is calculated for each bout using the corresponding accuracy of the given weight class from the prior calendar year. As an example, the expected distance strike accuracy for a Lightweight bout in 2025 is the total distance strike accuracy from all distance strikes thrown in Lightweight bouts in 2024. Expected clinch and ground strike accuracy is computed analogously. Also, for all Catchweight bouts (since there are so few) and for all fights in the debut year of a weight class, the expected accuracy metrics are calculated using all fights from the prior calendar year.</p>
<p>With this methodology, the updated formula for SAOE for a given fighter <span class="math inline">\(f\)</span> is:</p>
<span class="math display">\[\begin{aligned}

SAOE_f &amp;= \text{Significant strike accuracy}_f - \text{Expected significant strike accuracy}_f \\

&amp;= \frac{\text{Significant strikes landed}_f}{\text{Significant strikes attempted}_f} - \frac{\text{Expected significant strikes landed}_f}{\text{Significant strikes attempted}_f} \\

&amp;= \frac{\text{Significant strikes landed}_f - \text{Expected significant strikes landed}_f}{\text{Significant strikes attempted}_f}

\end{aligned}\]</span>
<p>Now, let <span class="math inline">\(B_f\)</span> be the set of UFC bouts for fighter <span class="math inline">\(f\)</span>, and let the prior year’s distance/clinch/ground strike accuracy be for the associated weight class for bout <span class="math inline">\(b\)</span>. Then, the formula for the expected number of significant strikes landed for the entire UFC career of fighter <span class="math inline">\(f\)</span> is:</p>
<span class="math display">\[\begin{array}{l}

\text{Expected significant strikes landed}_f = \\

\sum_{b \in B_f} \text{Expected distance strikes landed}_{f,b} + \text{Expected clinch strikes landed}_{f,b} \\
+ \text{Expected ground strikes landed}_{f,b} = \\

\sum_{b \in B_f} \text{Distance significant strike attempts}_{f,b} * \text{prior year distance strike accuracy}_b \\
+ \text{Clinch significant strike attempts}_{f,b} * \text{prior year clinch strike accuracy}_b \\
+ \text{Ground significant strike attempts}_{f,b} * \text{prior year ground strike accuracy}_b

\end{array}\]</span>
<p>For those who do not follow the notation, the expected number of significant strikes landed for a given fighter in a single bout is the sum of the expected number of distance, clinch, and ground significant strikes landed. Next, the expected number of distance strikes landed is the number of distance significant strike attempts times the distance strike accuracy for the corresponding weight class in the prior year (and so on for expected clinch and ground strikes). Then, summing those values across all bouts in the given fighter’s career yields the expected number of significant strikes landed, which can be plugged into the equation above for <span class="math inline">\(SAOE_f\)</span>.</p>
</section>
<section id="how-saoe-improves-upon-strike-accuracy" class="level1">
<h1>How SAOE improves upon strike accuracy</h1>
<p>The objective of this section is to illustrate how SAOE improves upon strike accuracy as a more informative composite measure of striking precision while maintaining interpretability.</p>
<p>To start, consider Sean O’Malley’s strike accuracy and SAOE in the table below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<caption>Sean O'Malley UFC Career Striking Statistics (as of March 01, 2025)</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Strike Accuracy</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SAOE</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Distance % of Strike Attempts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">61.5%</td>
<td style="text-align: center;">+18.5%</td>
<td style="text-align: center;">95.8%</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Strike accuracy alone does not provide any context, meaning it is unclear if O’Malley’s accuracy is high or low because there is no point of reference. SAOE, on the other hand, contains that context and depicts how much more accurate O’Malley is than the aggregate of his peers. In this case, O’Malley’s SAOE of +18.5% indicates that his strike accuracy is 18.5 percentage points higher than expected; hence, his expected strike accuracy based on the distribution of distance, clinch, and ground strikes he throws is: 61.5% - 18.5% = 43.0%.</p>
<p>Comparing strike accuracy between fighters can further exacerbate the issue, as seen in the table below. Jailton Almeida has a noticeably higher strike accuracy than Ciryl Gane. However, that difference in strike accuracy is largely driven by striking tendencies - Almeida throws nearly all his strikes from the clinch or ground while Gane strikes almost exclusively from distance. When accounting for the inherent differences in distance, clinch, and ground strikes, SAOE shows that Gane is clearly the more precise striker, as we would expect.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<caption>UFC Career Striking Statistics (as of March 01, 2025)</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Fighter</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Strike Accuracy</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SAOE</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Distance % of Strike Attempts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Jailton Almeida</td>
<td style="text-align: center;">66.8%</td>
<td style="text-align: center;">-2.9%</td>
<td style="text-align: center;">13.6%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Ciryl Gane</td>
<td style="text-align: center;">61.3%</td>
<td style="text-align: center;">+13.7%</td>
<td style="text-align: center;">92.3%</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>The table below shows Pearson correlation coefficients that describe the strength and direction of the linear relationships between striking metric (i.e.&nbsp;strike accuracy and SAOE) and striking tendencies (i.e.&nbsp;percent of strikes thrown at distance, in the clinch, or on the ground). Pearson correlation coefficients range from -1 to 1 such that positive numbers indicate a positive linear relationship (and vice versa for negative numbers) and 0 indicates no linear relationship.</p>
<p>As we can see, strike accuracy is moderately correlated with striking tendencies, but SAOE is effectively uncorrelated with the distribution of a fighter’s strike attempts. This property of SAOE is desirable because, unlike strike accuracy, it allows for meaningful comparisons between fighters across striking styles and tendencies. Put another way, a fighter’s strike accuracy can be artificially inflated by being an average ground striker who only throws ground strikes. However, that is not possible with SAOE - this hypothetical fighter would have to be an above average ground striker to have a positive SAOE.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<caption>Pearson Correlation Coefficients (among fighters with 300+ significant strike attempts and at least 1 bout since 2022)</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Strike Accuracy</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SAOE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Distance % of strike attempts</td>
<td style="text-align: center;">-0.460</td>
<td style="text-align: center;">-0.096</td>
</tr>
<tr class="even">
<td style="text-align: center;">Clinch % of strike attempts</td>
<td style="text-align: center;">0.332</td>
<td style="text-align: center;">0.138</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Ground % of strike attempts</td>
<td style="text-align: center;">0.361</td>
<td style="text-align: center;">0.029</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Finally, the table below shows the top 10 fighters with the highest UFC career SAOE. Unlike the top 10 in strike accuracy shown in a prior table, this table features almost exclusively elite strikers, which is a positive sign for the SAOE metric’s ability to meaningfully quantify striking precision.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<caption>UFC Career SAOE Top 10 (among fighters with 300+ significant strike attempts and at least 1 bout since 2022)</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Fighter</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SAOE</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Strike accuracy</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Distance % of strike attempts</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Significant strikes attempts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Sean O'Malley</td>
<td style="text-align: center;">+ 18.5%</td>
<td style="text-align: center;">61.5%</td>
<td style="text-align: center;">95.8%</td>
<td style="text-align: center;">1,645</td>
</tr>
<tr class="even">
<td style="text-align: center;">Chris Gutierrez</td>
<td style="text-align: center;">+ 16.5%</td>
<td style="text-align: center;">59.1%</td>
<td style="text-align: center;">95.7%</td>
<td style="text-align: center;">1,384</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Justin Gaethje</td>
<td style="text-align: center;">+ 15.2%</td>
<td style="text-align: center;">59.2%</td>
<td style="text-align: center;">91.0%</td>
<td style="text-align: center;">1,628</td>
</tr>
<tr class="even">
<td style="text-align: center;">Alex Pereira</td>
<td style="text-align: center;">+ 14.4%</td>
<td style="text-align: center;">63.1%</td>
<td style="text-align: center;">86.9%</td>
<td style="text-align: center;">921</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Ciryl Gane</td>
<td style="text-align: center;">+ 13.7%</td>
<td style="text-align: center;">61.3%</td>
<td style="text-align: center;">92.3%</td>
<td style="text-align: center;">1,467</td>
</tr>
<tr class="even">
<td style="text-align: center;">Paulo Costa</td>
<td style="text-align: center;">+ 13.0%</td>
<td style="text-align: center;">58.3%</td>
<td style="text-align: center;">91.5%</td>
<td style="text-align: center;">1,337</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Shara Magomedov</td>
<td style="text-align: center;">+ 12.8%</td>
<td style="text-align: center;">62.4%</td>
<td style="text-align: center;">86.7%</td>
<td style="text-align: center;">633</td>
</tr>
<tr class="even">
<td style="text-align: center;">Gabriel Santos</td>
<td style="text-align: center;">+ 12.7%</td>
<td style="text-align: center;">60.6%</td>
<td style="text-align: center;">82.9%</td>
<td style="text-align: center;">368</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Gunnar Nelson</td>
<td style="text-align: center;">+ 12.6%</td>
<td style="text-align: center;">61.1%</td>
<td style="text-align: center;">66.0%</td>
<td style="text-align: center;">453</td>
</tr>
<tr class="even">
<td style="text-align: center;">Jon Jones</td>
<td style="text-align: center;">+ 12.3%</td>
<td style="text-align: center;">58.9%</td>
<td style="text-align: center;">72.2%</td>
<td style="text-align: center;">2,655</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="components-of-saoe" class="level1">
<h1>Components of SAOE</h1>
<p>SAOE serves as a composite measure of striking precision across all strikes. However, breaking SAOE into its distance, clinch, and ground striking components is also informative. The formula for, say, Distance SAOE is the same as SAOE, minus the clinch and ground strikes. Hence, Distance SAOE is interpreted as the percentage point difference between observed and expected <em>distance</em> strike accuracy. Clinch SAOE and Ground SAOE are interpreted similarly.</p>
<p>The table below shows the UFC’s top 10 in SAOE alongside each fighter’s Distance, Clinch, and Ground SAOE. We can see that Sean O’Malley predominantly strikes from distance, but his clinch and ground striking precision has been strong so far. However, while Chris Gutierrez also throws the majority of his strikes from distance, the precision of his clinch and ground striking has been lacking. Thus, breaking SAOE into its components can highlight the different strengths and weaknesses of a fighter’s striking game.</p>
<div class="cell preview-image" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/saoe-table.png" class="img-fluid figure-img" width="1176"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="limitations-of-saoe" class="level1">
<h1>Limitations of SAOE</h1>
<p>While SAOE offers a clear improvement over strike accuracy and has many desirable properties, this version of SAOE is based on publicly available data and thus far from perfect. For instance, rather than only partitioning strikes based on whether they were thrown from distance, in the clinch, or on the ground, we would also preferably distinguish between the strike type (i.e.&nbsp;punch, kick, knee, elbow) and the target (i.e.&nbsp;opponent’s head, body, or legs). All of these different attributes of a strike are presumably associated with an inherently different accuracy that SAOE would ideally account for, but unfortunately, current publicly available data does not provide that level of granularity.</p>
</section>
<section id="next-steps" class="level1">
<h1>Next steps</h1>
<p>The natural follow on to SAOE is Strike Defense Over Expected (SDOE). Offensive striking only tells half the story of striking, so exploring how strike defense (defined as the number of significant strikes a fighter’s opponent misses divided by the number of significant strikes the opponent attempts) compares to an SDOE metric that accounts for the distribution of strike attempts faced at distance, in the clinch, or on the ground - alongside the associated expected strike defense of each - will hopefully be similarly valuable.</p>
<p>Finally, once both SAOE and SDOE are developed as composite offensive and defensive striking metrics, respectively, more work can be done to attempt to combine these metrics into a single, unified advanced striking metric that considers both offensive and defensive striking prowess relative to expectation. Stay tuned for more work on this front - the best way to do so is to follow me on Twitter at <a href="https://x.com/NateLatshaw"><span class="citation" data-cites="NateLatshaw">@NateLatshaw</span></a>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'alternate';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>