---
title: "Predicting UFC judging decisions"
description: |
  Introducing a new fight evaluation tool: a machine learning model that predicts judging decisions by round in the UFC.
author:
  - name: Nate Latshaw
    url: {}
date: 02-03-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
rm(list = ls())
gc()

library(data.table)
library(lubridate)
library(ggplot2)
library(ranger)

data_path <- paste0(getwd(), '/predicting-ufc-judging-scores_files/')

# load data
df <- readRDS(paste0(data_path, 'round_decisions_and_stats_20210203.RDS'))




```

Blog named after first Reddit comment on this work. I had to honor one of Reddit's finest with this blog. Link to [proof](https://www.reddit.com/r/MMA/comments/iy2z3i/introducing_a_new_fight_evaluation_tool_a_machine/g6abz5w?utm_source=share&utm_medium=web2x&context=3). Comment was the very first of over 100 comments. It has also received the second most upvotes of all comments.



